/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedHistoricoRouteImport } from './routes/_authenticated/historico'
import { Route as AuthenticatedEntradaRouteImport } from './routes/_authenticated/entrada'
import { Route as AuthenticatedDispositivosRouteImport } from './routes/_authenticated/dispositivos'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedNumerosIndexRouteImport } from './routes/_authenticated/numeros.index'
import { Route as AuthenticatedFuncionariasIndexRouteImport } from './routes/_authenticated/funcionarias.index'
import { Route as AuthenticatedNumerosIdRouteImport } from './routes/_authenticated/numeros.$id'
import { Route as AuthenticatedFuncionariasIdRouteImport } from './routes/_authenticated/funcionarias.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedHistoricoRoute = AuthenticatedHistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEntradaRoute = AuthenticatedEntradaRouteImport.update({
  id: '/entrada',
  path: '/entrada',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDispositivosRoute =
  AuthenticatedDispositivosRouteImport.update({
    id: '/dispositivos',
    path: '/dispositivos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNumerosIndexRoute =
  AuthenticatedNumerosIndexRouteImport.update({
    id: '/numeros/',
    path: '/numeros/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFuncionariasIndexRoute =
  AuthenticatedFuncionariasIndexRouteImport.update({
    id: '/funcionarias/',
    path: '/funcionarias/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedNumerosIdRoute = AuthenticatedNumerosIdRouteImport.update({
  id: '/numeros/$id',
  path: '/numeros/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFuncionariasIdRoute =
  AuthenticatedFuncionariasIdRouteImport.update({
    id: '/funcionarias/$id',
    path: '/funcionarias/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/dispositivos': typeof AuthenticatedDispositivosRoute
  '/entrada': typeof AuthenticatedEntradaRoute
  '/historico': typeof AuthenticatedHistoricoRoute
  '/funcionarias/$id': typeof AuthenticatedFuncionariasIdRoute
  '/numeros/$id': typeof AuthenticatedNumerosIdRoute
  '/funcionarias/': typeof AuthenticatedFuncionariasIndexRoute
  '/numeros/': typeof AuthenticatedNumerosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/dispositivos': typeof AuthenticatedDispositivosRoute
  '/entrada': typeof AuthenticatedEntradaRoute
  '/historico': typeof AuthenticatedHistoricoRoute
  '/funcionarias/$id': typeof AuthenticatedFuncionariasIdRoute
  '/numeros/$id': typeof AuthenticatedNumerosIdRoute
  '/funcionarias': typeof AuthenticatedFuncionariasIndexRoute
  '/numeros': typeof AuthenticatedNumerosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/dispositivos': typeof AuthenticatedDispositivosRoute
  '/_authenticated/entrada': typeof AuthenticatedEntradaRoute
  '/_authenticated/historico': typeof AuthenticatedHistoricoRoute
  '/_authenticated/funcionarias/$id': typeof AuthenticatedFuncionariasIdRoute
  '/_authenticated/numeros/$id': typeof AuthenticatedNumerosIdRoute
  '/_authenticated/funcionarias/': typeof AuthenticatedFuncionariasIndexRoute
  '/_authenticated/numeros/': typeof AuthenticatedNumerosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/dispositivos'
    | '/entrada'
    | '/historico'
    | '/funcionarias/$id'
    | '/numeros/$id'
    | '/funcionarias/'
    | '/numeros/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/dispositivos'
    | '/entrada'
    | '/historico'
    | '/funcionarias/$id'
    | '/numeros/$id'
    | '/funcionarias'
    | '/numeros'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/dashboard'
    | '/_authenticated/dispositivos'
    | '/_authenticated/entrada'
    | '/_authenticated/historico'
    | '/_authenticated/funcionarias/$id'
    | '/_authenticated/numeros/$id'
    | '/_authenticated/funcionarias/'
    | '/_authenticated/numeros/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/historico': {
      id: '/_authenticated/historico'
      path: '/historico'
      fullPath: '/historico'
      preLoaderRoute: typeof AuthenticatedHistoricoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/entrada': {
      id: '/_authenticated/entrada'
      path: '/entrada'
      fullPath: '/entrada'
      preLoaderRoute: typeof AuthenticatedEntradaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dispositivos': {
      id: '/_authenticated/dispositivos'
      path: '/dispositivos'
      fullPath: '/dispositivos'
      preLoaderRoute: typeof AuthenticatedDispositivosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/numeros/': {
      id: '/_authenticated/numeros/'
      path: '/numeros'
      fullPath: '/numeros/'
      preLoaderRoute: typeof AuthenticatedNumerosIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/funcionarias/': {
      id: '/_authenticated/funcionarias/'
      path: '/funcionarias'
      fullPath: '/funcionarias/'
      preLoaderRoute: typeof AuthenticatedFuncionariasIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/numeros/$id': {
      id: '/_authenticated/numeros/$id'
      path: '/numeros/$id'
      fullPath: '/numeros/$id'
      preLoaderRoute: typeof AuthenticatedNumerosIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/funcionarias/$id': {
      id: '/_authenticated/funcionarias/$id'
      path: '/funcionarias/$id'
      fullPath: '/funcionarias/$id'
      preLoaderRoute: typeof AuthenticatedFuncionariasIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDispositivosRoute: typeof AuthenticatedDispositivosRoute
  AuthenticatedEntradaRoute: typeof AuthenticatedEntradaRoute
  AuthenticatedHistoricoRoute: typeof AuthenticatedHistoricoRoute
  AuthenticatedFuncionariasIdRoute: typeof AuthenticatedFuncionariasIdRoute
  AuthenticatedNumerosIdRoute: typeof AuthenticatedNumerosIdRoute
  AuthenticatedFuncionariasIndexRoute: typeof AuthenticatedFuncionariasIndexRoute
  AuthenticatedNumerosIndexRoute: typeof AuthenticatedNumerosIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDispositivosRoute: AuthenticatedDispositivosRoute,
  AuthenticatedEntradaRoute: AuthenticatedEntradaRoute,
  AuthenticatedHistoricoRoute: AuthenticatedHistoricoRoute,
  AuthenticatedFuncionariasIdRoute: AuthenticatedFuncionariasIdRoute,
  AuthenticatedNumerosIdRoute: AuthenticatedNumerosIdRoute,
  AuthenticatedFuncionariasIndexRoute: AuthenticatedFuncionariasIndexRoute,
  AuthenticatedNumerosIndexRoute: AuthenticatedNumerosIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
